name: pasada_admin_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  desktop_webview_window: ^0.2.3
  supabase_flutter: ^2.8.4
  connectivity_plus: ^6.1.3
  supabase: ^2.6.3
  google_maps_flutter: ^2.12.1
  google_maps_flutter_web: ^0.5.12
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17
  geolocator: ^13.0.4
  geocoding: ^3.0.0
  flutter_typeahead: ^5.2.0
  location: ^8.0.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  h3_flutter: ^0.6.6
  dio: ^5.8.0+1
  get: ^4.7.2
  flutter_google_maps_webservices: ^1.1.1
  flutter_polyline_points: ^2.1.0
  http: ^1.3.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  supabase_flutter: ^2.8.4

flutter:
  uses-material-design: true
  
fonts:
  - family: Inter
    fonts:
      - asset: fonts/Inter_18pt-Black.ttf
        weight: 900
      - asset: fonts/Inter_18pt-BlackItalic.ttf
        weight: 900
        style: italic
      - asset: fonts/Inter_18pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_18pt-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: fonts/Inter_18pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_18pt-Italic.ttf
        weight: 400
        style: italic
      - asset: fonts/Inter_18pt-Light.ttf
        weight: 300
      - asset: fonts/Inter_18pt-LightItalic.ttf
        weight: 300
        style: italic
      - asset: fonts/Inter_24pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_24pt-Regular.ttf
        weight: 400
      - asset: fonts/Inter_28pt-Bold.ttf
        weight: 700
      - asset: fonts/Inter_28pt-Regular.ttf
        weight: 400